run:
  timeout: 1m

linters:
  enable:
    - lll
    - gofmt
    - revive
    - unparam

linters-settings:
  revive:
    rules:
      - name: unexported-return
        severity: ignore
  lll:
    line-length: 180
