name: tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    name: testing and linting
    steps:
      - uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: 1.22

      - run: go test -race -coverprofile="coverage.txt" -covermode=atomic ./...

      - name: lint
        if: github.event_name == 'pull_request'
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          skip-build-cache: true
          skip-pkg-cache: true

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: leoviggiano/translator